### ISSUE TITLE
Support Redo/Undo for deleting constraints

### ISSUE THREAD

**Issue by MingweiSamuel** [SudokuStudio/SudokuStudio#11]

**Comment by MingweiSamuel** [comment]
IIRC the issue is that the state-manager does not apply updates "atomically". Specifically it change a specific key (path) in the update, runs all the watchers on that path, then continues to the next key, resulting in a bunch of intermediate states. This is an issue by itself, but with removing/adding constraints those intermediate states are invalid and cause errors in the front-end.

**Comment by wooferzfg** [comment]
I think I was able to resolve the front end issue without changing the `StateManager` code. It might be worth updating the state manager to resolve the underlying issue, but I'm not confident enough in my understanding of that code to make a change like that myself yet.
