### ISSUE TITLE
✨ Feature: Diagonal connection between orthogonally disconnected killer cages

### ISSUE THREAD

**Issue by DancingGrumpyCat** [SudokuStudio/SudokuStudio#16]
### What's Your Feature Idea?

<img width="668" alt="image" src="https://user-images.githubusercontent.com/67075625/126856116-98bbea48-2865-44bd-a943-8736aaa78aac.png">

It is currently unclear whether the three-cell cage at the bottom is on its own or connected. I recommend adding a small diamond to the killer cage shape at corners where this occurs (where exactly two corners of the same killer cage touch, and they don't touch directly via any edge)

**Comment by MingweiSamuel** [comment]
Can you do a quick mspaint sketch of what this would look like? To make sure I'm imagining what you are

**Comment by DancingGrumpyCat** [comment]
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/67075625/127427866-042f6f01-3d06-49cf-951c-c597ae035b20.png">

Not the right proportions—the connection here is large enough it might get in the way—but this is the idea.

**Comment by MingweiSamuel** [comment]
How's this?
![image](https://user-images.githubusercontent.com/6778341/127428826-01ba1a15-0456-4643-a3d0-1db84df2d1a1.png)

(I would show two crossing, but they're broken right now in the positive direction)

**Comment by MingweiSamuel** [comment]
👌
![image](https://user-images.githubusercontent.com/6778341/127430722-80e19753-17ea-4ca5-b9aa-ae669f834c43.png)
