### ISSUE TITLE
🐞 Bug: inconsistent corner rounding on whisper and palindrome constraints

### ISSUE THREAD

**Issue by DancingGrumpyCat** [SudokuStudio/SudokuStudio#19]
### Describe the Bug

<img width="932" alt="image" src="https://user-images.githubusercontent.com/67075625/126860092-0152e4e0-931b-4a96-bc6f-a8f58bfe674b.png">

The top left corner is the start and end point of the whisper/palindrome.

Visually, for the whipser, the start/end point doesn't matter if the path is cyclic, so the Bézier rounding shouldn't differentiate it.

For the palindrome, maybe it should not be allowed to self-intersect, as that causes ambiguity as to where the start point is.

### Reproduction steps

Whisper or palindrome starting and ending on the same cell.

### Sudoku Studio Save Url

https://www.sudokustudio.net/?b=N4Ig5gTglgJiBcoDusAuALBBOANCdAplGOqtgL54EA2BAtgQHaoDOCoAjOyKgJ4AOBBOGhw8AewgwCEBBwAMHSiABM3PoOEAjcQA8QEqTLnz5eAG4BDagFchiEChgYEAZjyFipN%2BWUL1AvbgUOZMbIbSsvAqKvJ%2BXA4aQQBmUNS0YiCSkQgqCn5qiYHCAMaSjMYRxtGmfq4BmvAgJUyolVlGUbFxeBwALA1BZdSS4R058Pl4rgCsiioA7CpYC4PC%2FNZQjDAQ4gwG49UAbGYgVrb2oH0crliuR4tYR9zyue4gCa4qeIWu7%2FXRPp4AbRVy%2BPzXAAcf0hNxBoCSwggTC0lkYB2y1UhPRAfxmrlhCyWAIRxSaSHQUBYglkVSiC1O5zs3EhfSORzmWA4kJeuQ4vTcp1%2B%2FNxuW%2BIBBeXBviAA%3D

### Sudoku Studio Version

6c8747f

### Browser Version

Firefox 90.0.1 (but it should be the same in any browser)

### OS Version

macOS 11.4 (but it should be the same in any OS)

**Comment by MingweiSamuel** [comment]
I think self-intersecting palindromes could be interesting for setting puzzles, but of course its up to the setter to use that wisely.
