### ISSUE TITLE
🐞 Bug: Grid resizing inappropriately for Quadruples

### ISSUE THREAD

**Issue by DancingGrumpyCat** [SudokuStudio/SudokuStudio#32]
### Describe the Bug

The grid should not get smaller for quadruples clues *until* one is added to the edge, and it should get bigger again if one on the edge is removed such that none exist on the edge.
<img width="1440" alt="grid shouldn't resize like this" src="https://user-images.githubusercontent.com/67075625/127325496-798a38fb-090e-4b9e-9da0-0f7c2be37153.png">

### Reproduction steps

Add quadruples clues to menu

### Sudoku Studio Save Url

https://www.sudokustudio.net/?b=N4Ig5gTglgJiBcoDusAuALBBOANCdAplGOqtgL54EA2BAtgQHaoDOCoAjOyKgJ4AOBBOGhw8AewgwCEBBwAMHSiABM3PoOEAjcQA8QEqTLnz5eAG4BDagFchiEChgYEAZjyFipN%2BWUL1AvbgUOZMbIbSsvAqKvJ%2BXA4aQQBmUNS0YiCSkQgqCn5qiYHCAMaSjMYRxtGmfq4BmvAgJUyolVlGUbFxeBwALA1BZdSS4R058Pl4eQDsc32msYPCEExalowG49UAHGYgVrb2nH2uHDszAKwX3PIIl329CH0AbNPPM3j18K64IAPwBZ4S7PDh4F5udwgGZuR4gHa5F5%2BeQzM7yF7yFQwhx3eCXN4gBIvS7veAzOHfK54AEzJG9VwzDgvfozLAA0C4uEJEmqBAE74cHkAlR9ZSueSucUcLA7DgJDm5J6TMG86Iq75nanPfYgwF%2FCF4v7Yl5%2FBFknZiy4S5nkjjYhXwDFK5mkl4qL73KEAvqi6kqS6%2FVGKM0O2JK6Wk84e6Kff5uJG%2BL7yHZ7FSSy660BJYQARxslhgEBs%2FFoW2y1Tl%2B0Odm4ctuisJPl6mZAuJ5RL8Idb92dyj68u70SVrmU13rZKVFrwsvHXPuyh27MHc7xC67uNjCQtiZArhUGNiHBFLezTQIoU2VSiQIO1hrDm%2BqCLBF6uKfdl62PfL5AL0fz7wGY3wA6Ev2fXxfCAA

### Sudoku Studio Version

cdb9880

### Browser Version

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:90.0) Gecko/20100101 Firefox/90.0

### OS Version

MacIntel

**Comment by MingweiSamuel** [comment]
Right now there isn't a way to dynamically affect the margin, probably wait for v1.1. But tbh quadruples on the edges (and especially on corners) aren't very interesting, so we could just crop them off

**Comment by DancingGrumpyCat** [comment]
Cropping them—that is, cutting the quadruple circle in half and writing the numbers in the clue slightly lower—makes sense to me. You don't need to worry about 3+ digits fitting since only two digits can fit on the edge anyway.

**Comment by DancingGrumpyCat** [comment]
<img width="683" alt="image" src="https://user-images.githubusercontent.com/67075625/127392304-df067ab7-4e26-4a7e-aadc-5cb01448064a.png">

Shouldn't the outside outline be visible? maybe put the very outside outline on the top layer.

**Comment by MingweiSamuel** [comment]
Mhm yeah probably

**Comment by MingweiSamuel** [comment]
Hows this?
![image](https://user-images.githubusercontent.com/6778341/127416309-3213307c-1ff9-4470-889d-4d7feab18fb6.png)

**Comment by DancingGrumpyCat** [comment]
They're a bit squished & close to the margin—they could eventually be a bit smaller. That said, I've never seen a quadruples puzzle with clues on the edge, so we can probably wait until people start using it and see what their opinions are.
