### ISSUE TITLE
🐞 Bug: broken between lines

### ISSUE THREAD

**Issue by DancingGrumpyCat** [SudokuStudio/SudokuStudio#37]
### Describe the Bug

<img width="672" alt="image" src="https://user-images.githubusercontent.com/67075625/127547227-db357bb7-b739-4927-af6a-574f5abb00fb.png">

Some between lines are broken.

### Sudoku Studio Save Url

https://www.sudokustudio.net/?b=N4Ig5gTglgJiBcoDusAuALBBOANCdAplGOqtgL54EA2BAtgQHaoDOCoAjOyKgJ4AOBBOGhw8AewgwCEBBwAMHSiABM3PoOEAjcQA8QEqTLnz5eAG4BDagFchiEChgYEAZjyFipN%2BWUL1AvbgUOZMbIbSsvAqKvJ%2BXA4aQQBmUNS0YiCSkQgqCn5qiYHCAMaSjMYRxtGmfq4BmvAgJUyolVlGUbFxeBwALA1BZdSS4R058Pl4eQBsc1gL8gCsg9oEqEgETAbj1UtmIFa29qAzrjPyrn19ABwA7Nzyub1yHNNyuCD10Td4A%2FDnPAreB9JZ4GYIJZLZQ3VwcGY3LA3PqFUBPaJvEAJGLvSZ9eLLFRYInIx5uF6TFS42J4b5E5SueQ3DhQmYcfwOdF9TEJPqfQpLO4MpZXJb9FR3VEgdFwimuFQMu58jiuVzIiGctzuLEIFG4sW0hAXXy%2BPAMVCWdRQVC0YQAYRGFQABABlGwwcQAaxsO0sNgwkmEBBK6HEBDG0hYJWg%2FFQUHEjGEADlJHRrE6So6CE6WO6vTYnRAbLQWE7LPx%2BNReAA6EC%2BIA%3D%3D

### Sudoku Studio Version

4b66b26

### Browser Version

Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:90.0) Gecko/20100101 Firefox/90.0

### OS Version

MacIntel

**Comment by wooferzfg** [comment]
Is there an easy way to reproduce this? I don't see any issues when using Chrome. 
![Screenshot_20220130-094503_Chrome](https://user-images.githubusercontent.com/8262173/151706645-4cd335a7-9ce5-4dcd-8725-4f0340f897cb.png)

**Comment by wooferzfg** [comment]
From a Discord conversation: this issue appears to happen in Firefox but not in Chrome.
