### ISSUE TITLE
Recolor white svg with CSS

### ISSUE THREAD

**Issue by DancingGrumpyCat** [SudokuStudio/SudokuStudio#5]
I've made all the SVG files white, so they can be recolored via CSS.

**Comment by MingweiSamuel** [comment]
f0abf2bfdbce729e81ab75f95d2fafb7cf65c54c
ea95f4f25175f692d069c51f36d1edec65172bb5

May change to encode the colors into the css in the future but -webkit-mask-image should be fine for now
