### ISSUE TITLE
🐞 Bug: ctrl+asdw

### ISSUE THREAD

**Issue by ScottStrosahl** [SudokuStudio/SudokuStudio#58]
### Describe the Bug

ctrl+a moves the cursor to the left, when I would expect it to select all (ctrl+s and ctrl+d also move down/right)
however, ctrl+w closes the tab (as I would expect)

### Sudoku Studio Version

0c0bad9

### Browser Version

Chrome 97.0.4692.99

### OS Version

Win 10

**Comment by wooferzfg** [comment]
Fixed in https://github.com/SudokuStudio/SudokuStudio/commit/52731d639acec70aa77c09b574eab5b974c012a1
