### ISSUE TITLE
🐞 Bug: Odd/Even Overlap

### ISSUE THREAD

**Issue by ScottStrosahl** [SudokuStudio/SudokuStudio#59]
### Describe the Bug

![image](https://user-images.githubusercontent.com/72059631/152443756-c707ee0e-b230-496e-906e-fe56c451d416.png)
Odd and even can overlap each other.  Clearly a cell can't be both odd and even, so it probably makes the most sense for the even to be removed when adding an odd over the top, or vice versa.

### Sudoku Studio Version

0c0bad9

### Browser Version

Chrome/97.0.4692.99

### OS Version

Win 10

**Comment by wooferzfg** [comment]
The fix for this issue and https://github.com/SudokuStudio/SudokuStudio/issues/47 will likely be similar.
