### ISSUE TITLE
🐞 Bug: Renban drawing

### ISSUE THREAD

**Issue by ScottStrosahl** [SudokuStudio/SudokuStudio#60]
### Describe the Bug

When drawing a renban line, if you go back over part of the line that is already drawn, it erases everything past that point. If you wanted to draw a T shape, for example, you wouldn't be able to.
Something like this image, but all connected. ![image](https://user-images.githubusercontent.com/72059631/152445219-c7aeca8d-743b-446e-991c-713a69133201.png)

https://user-images.githubusercontent.com/72059631/152445166-4b22db67-fc4f-4687-a44d-0befa26745ad.mp4

.

### Sudoku Studio Version

0c0bad9

### Browser Version

Chrome/97.0.4692.99

### OS Version

Win 10

**Comment by wooferzfg** [comment]
This issue appears to be similar to https://github.com/SudokuStudio/SudokuStudio/issues/20.
