### ISSUE TITLE
🐞 Bug: Removing an arrow line takes two clicks - first click places a circle, second removes circle and line

### ISSUE THREAD

**Issue by dclamage** [SudokuStudio/SudokuStudio#61]
### Describe the Bug

If you draw an arrow, the first thing you do is place a circle. Then you click again and drag from the circle to place the arrow line. If you want to then remove the arrow line, the natural thing to do is click on the line again. However, this places a circle in that cell instead. But then, when you click the circle it removes both the circle and the line.

### Reproduction steps

1. Add the arrow constraint and select it
2. Click a cell to place a circle
3. Drag from the cell to place a line
4. Click on a line cell and see that it places a circle.
5. Click on the newly placed circle, and see that it removes both the circle and the line.

Expected behavior: Up to discussion, but this feels buggy to me as is. The ability to place overlapping circles is important, but so is the ability to delete a line. The cleanest solution which may not be the most friendly would be to only delete arrows if you click on their circles. Clicking the line places a circle there and clicking again only removes the circle and not the line.

### Sudoku Studio Save Url

https://sudokustudio.github.io/SudokuStudio/?b=N4Ig5gTglgJiBcoDusAuALBBOANCdAplGOqtgL54EA2BAtgQHaoDOCoAjOyKgJ4AOBBOGhw8AewgwCEBBwAMHSiABM3PoOEAjcQA8QEqTLnz5eAG4BDagFchiEChgYEAZjyFipN%2BWUL1AvbgUOZMbIbSsvAqKvJ%2BXA4aQQBmUNS0YiCSkQgqCn5qiYHCAMaSjMYRxtGmfq4BmvAgJUyolVlGUbFxeBwALA1BZdSS4R058Pl4rqbyAKyxHHNzg8KWEBDiSAbj1VhmIFa29pwAbPKnlwAcc65X3Fo21Frc8m5YyjowvK%2Fvvbm4VRyD6%2BUFAA%3D%3D

### Sudoku Studio Version

26efaf0

### Browser Version

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36

### OS Version

Win32

**Comment by wooferzfg** [comment]
> The cleanest solution which may not be the most friendly would be to only delete arrows if you click on their circles. Clicking the line places a circle there and clicking again only removes the circle and not the line.

I implemented this in https://github.com/SudokuStudio/SudokuStudio/commit/40ea34b1b646fc3debd6e52002df9eb69475aae5.

**Comment by dclamage** [comment]
I think it can be closed. We'll likely want to revisit constraint placement, selection, modification, and deletion in the future but that's a larger task.
