### ISSUE TITLE
🐞 Bug: Not clear why top 'buttons' don't work

### ISSUE THREAD

**Issue by alexmojaki** [SudokuStudio/SudokuStudio#84]
### Describe the Bug

On sudokustudio.net, the top bar says:

- Solving/Setting
- New Grid
- Export
- Light/dark
- Help
- Settings

Only "New Grid" works. Based on the code:

https://github.com/SudokuStudio/SudokuStudio/blob/376a0a400f84c3698819b7df712cb0ac0a951b22/packages/web/src/svelte/header/Header.svelte#L7-L22

this seems known/intentional, but it's really confusing for a visitor. I spent way too long thinking that I was doing something wrong or that there had been a major invisible error. Did I miss something? Now my best guess is that they're just placeholders, but I don't know if that guess is correct and it's very strange either way. The project looks mature and polished in other ways, so this mismatch is very surprising and leaves me unsure about the status of the codebase.

I suggest removing the 'buttons' until the features are implemented, or at least adding a note somewhere (did I miss one?) explaining the situation. 

### Sudoku Studio Save Url

https://www.sudokustudio.net/?b=N4Ig5gTglgJiBcoDusAuALBBOANCdAplGOqtgL54EA2BAtgQHaoDOCoAjOyKgJ4AOBBOGhw8AewgwCEBBwAMHSiABM3PoOGRYAJQJgo4xiAlSZc%2BfLwA3AIbUArkMQh53N%2FFQQneLp%2B8EeGr%2BPiBYCF6hChEBvn6RgSAcABwxUeEhiSoeCcp%2BoADMaYkALMV4AKzlScEJvkWZvmWNqvGxqrXtKg25QdwAbNUA7NWpLRxV44PjIy0qzXWqk4sq070gDaAqsytjKxmLBWvtBTsne%2B0ly5fHoSVnTsrNhTknbaEFnR8Hl69376ULncfqEKn8CMpJoUeicFidrncvqUYXc4aCAZUkZUURC8NNQBU0YkKgjibdEv0cXiiXjSXghliQEMqUyicpZgSHsSgcSQRTyXiuXiefS6UyBUyucoxqB%2BuC8RiQP1Gf0%2BfT5UzFUMRUy1SBkuDyEbfB5QBpnOAoNYmGxTNJZPAVNkbPYnNwCmMOJU%2FCpjUl8jwBBaAGZQai0MQgST2hAqBQuxzOUAeEq%2BBDJPrwAp4BpDPDNFSVBD9PFyekICp4Ma4MIIPNJDyF%2F3F3zBL1JBqVpLNGsTBCppLTDNJWbZpKe3wZLvZbBBPwDp3poINMfzOtBSZN1Yt1SzYcqMarjL1gqNnN%2BEsbNs5zs5ns5yYDo6xnOzS8essbKf5jw1krz%2FNgmHEoV3zZp6yuCt82mP9ZgHEoxmAjIxzBdcQAqH1MR3CoGnbQkEBQyZ6wqaYmwqN9KgndDvyVX8FX7PEgLxBpL36Zp236SYu36GDBQYpVELxZD1TQoZMKZYIa2ZfihmaYchkmMchmmeshlmJttR3IYMnbA0Kz9DhgjNINhAAY0kRhzDtcxHUsPJNkDTR4BAUymFQKyozMB1snkPJnkci1zOoSRbU8mN4AUPJ5FVeQKiwZI5XUEznIAa0YYhSBMMKbKsEA7ETYplAPVZkhKLB7g5AKzKMFgCFMhxUCtIRrIdXL8rdFxJAwaoYCgWwwAQYN7Fqv1iu0j0OHuJKnJAFKoEYAaWoQNrXWcXIjSAA

### Sudoku Studio Version

376a0a4

### Browser Version

Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36

### OS Version

Linux x86_64

**Comment by wooferzfg** [comment]
Most of the buttons are just placeholders for now

**Comment by alexmojaki** [comment]
Thanks for the response! Is there any way that future visitors can discover/infer this for themselves without looking at the source code? Is there a README/issue/wiki/anything that I failed to notice myself? Are these features expected to be implemented in the near future?

**Comment by wooferzfg** [comment]
I think you're right that we should just remove the buttons for now

The general plan for this project is to get it to feature parity with f-puzzles.com before trying to publish it more widely. However, there's still a lot left to do before then, so I think it makes sense to make it more polished in the meantime
